I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/wasd.rpy", line 12, in script
    $ move_person(you, "N")
  File "game/wasd.rpy", line 12, in <module>
    $ move_person(you, "N")
NameError: name 'move_person' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/wasd.rpy", line 12, in script
    $ move_person(you, "N")
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-8.1.3-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/wasd.rpy", line 12, in <module>
    $ move_person(you, "N")
NameError: name 'move_person' is not defined

macOS-14.4.1-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
prototyping 1.0
Sat Oct 12 18:10:13 2024
